import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { delay } from 'rxjs/operators';
import { PreviousYearPaper, EXAM_MONTH, PAPER_PATTERN } from '../interfaces/paper.interfaces';

export const MOCK_PAPERS: PreviousYearPaper[] = [
  // ── SE Sem 3 — 2019 Pattern — November exams ─────────────────────────────
  {
    id: 'se3-dm-nov21',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2021,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Discrete Mathematics',
    subjectCode: 'SE-CE-301',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-dm-nov21/view',
  },
  {
    id: 'se3-ds-nov21',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2021,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Data Structures',
    subjectCode: 'SE-CE-302',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-ds-nov21/view',
  },
  {
    id: 'se3-de-nov21',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2021,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Digital Electronics & Logic Design',
    subjectCode: 'SE-CE-303',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-de-nov21/view',
  },
  {
    id: 'se3-coa-nov21',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2021,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Computer Organization & Architecture',
    subjectCode: 'SE-CE-304',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-coa-nov21/view',
  },
  {
    id: 'se3-java-nov21',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2021,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'OOP with Java',
    subjectCode: 'SE-CE-305',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-java-nov21/view',
  },
  {
    id: 'se3-dm-nov22',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Discrete Mathematics',
    subjectCode: 'SE-CE-301',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-dm-nov22/view',
  },
  {
    id: 'se3-ds-nov22',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Data Structures',
    subjectCode: 'SE-CE-302',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-ds-nov22/view',
  },
  {
    id: 'se3-de-nov22',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Digital Electronics & Logic Design',
    subjectCode: 'SE-CE-303',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-de-nov22/view',
  },
  {
    id: 'se3-coa-nov22',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Computer Organization & Architecture',
    subjectCode: 'SE-CE-304',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-coa-nov22/view',
  },
  {
    id: 'se3-java-nov22',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'OOP with Java',
    subjectCode: 'SE-CE-305',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-java-nov22/view',
  },
  {
    id: 'se3-dm-nov23',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Discrete Mathematics',
    subjectCode: 'SE-CE-301',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-dm-nov23/view',
  },
  {
    id: 'se3-ds-nov23',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Data Structures',
    subjectCode: 'SE-CE-302',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-ds-nov23/view',
  },
  {
    id: 'se3-de-nov23',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Digital Electronics & Logic Design',
    subjectCode: 'SE-CE-303',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-de-nov23/view',
  },

  // ── SE Sem 4 — 2019 Pattern — May exams ──────────────────────────────────
  {
    id: 'se4-toc-may22',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 4,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Theory of Computation',
    subjectCode: 'SE-CE-401',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se4-toc-may22/view',
  },
  {
    id: 'se4-dbms-may22',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 4,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Database Management Systems',
    subjectCode: 'SE-CE-402',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se4-dbms-may22/view',
  },
  {
    id: 'se4-mp-may22',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 4,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Microprocessors & Interfacing',
    subjectCode: 'SE-CE-403',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se4-mp-may22/view',
  },
  {
    id: 'se4-cn-may22',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 4,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Computer Networks',
    subjectCode: 'SE-CE-404',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se4-cn-may22/view',
  },
  {
    id: 'se4-os-may22',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 4,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Operating Systems',
    subjectCode: 'SE-CE-405',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se4-os-may22/view',
  },
  {
    id: 'se4-toc-may23',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 4,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Theory of Computation',
    subjectCode: 'SE-CE-401',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se4-toc-may23/view',
  },
  {
    id: 'se4-dbms-may23',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 4,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Database Management Systems',
    subjectCode: 'SE-CE-402',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se4-dbms-may23/view',
  },
  {
    id: 'se4-os-may24',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 4,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2024,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Operating Systems',
    subjectCode: 'SE-CE-405',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se4-os-may24/view',
  },

  // ── TE Sem 5 — 2019 Pattern — November exams ─────────────────────────────
  {
    id: 'te5-daa-nov22',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 5,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Design & Analysis of Algorithms',
    subjectCode: 'TE-CE-501',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te5-daa-nov22/view',
  },
  {
    id: 'te5-sp-nov22',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 5,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Systems Programming & Operating System',
    subjectCode: 'TE-CE-502',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te5-sp-nov22/view',
  },
  {
    id: 'te5-se-nov22',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 5,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Software Engineering',
    subjectCode: 'TE-CE-503',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te5-se-nov22/view',
  },
  {
    id: 'te5-wt-nov22',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 5,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Web Technology',
    subjectCode: 'TE-CE-504',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te5-wt-nov22/view',
  },
  {
    id: 'te5-cn-nov22',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 5,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Computer Networks',
    subjectCode: 'TE-CE-505',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te5-cn-nov22/view',
  },
  {
    id: 'te5-daa-nov23',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 5,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Design & Analysis of Algorithms',
    subjectCode: 'TE-CE-501',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te5-daa-nov23/view',
  },
  {
    id: 'te5-wt-nov23',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 5,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Web Technology',
    subjectCode: 'TE-CE-504',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te5-wt-nov23/view',
  },
  {
    id: 'te5-se-nov23',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 5,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Software Engineering',
    subjectCode: 'TE-CE-503',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te5-se-nov23/view',
  },

  // ── TE Sem 6 — 2019 Pattern — May exams ──────────────────────────────────
  {
    id: 'te6-cg-may23',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 6,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Computer Graphics',
    subjectCode: 'TE-CE-601',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te6-cg-may23/view',
  },
  {
    id: 'te6-ai-may23',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 6,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Artificial Intelligence',
    subjectCode: 'TE-CE-602',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te6-ai-may23/view',
  },
  {
    id: 'te6-mad-may23',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 6,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Mobile Application Development',
    subjectCode: 'TE-CE-603',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te6-mad-may23/view',
  },
  {
    id: 'te6-bda-may23',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 6,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Big Data Analytics',
    subjectCode: 'TE-CE-604',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te6-bda-may23/view',
  },
  {
    id: 'te6-ics-may23',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 6,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Information & Cyber Security',
    subjectCode: 'TE-CE-605',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te6-ics-may23/view',
  },
  {
    id: 'te6-ai-may24',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 6,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2024,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Artificial Intelligence',
    subjectCode: 'TE-CE-602',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te6-ai-may24/view',
  },
  {
    id: 'te6-mad-may24',
    branchName: 'Computer Engineering',
    academicYear: 'TE',
    semester: 6,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2024,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Mobile Application Development',
    subjectCode: 'TE-CE-603',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_te6-mad-may24/view',
  },

  // ── BE Sem 7 — 2019 Pattern — November exams ─────────────────────────────
  {
    id: 'be7-ml-nov22',
    branchName: 'Computer Engineering',
    academicYear: 'BE',
    semester: 7,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Machine Learning',
    subjectCode: 'BE-CE-701',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_be7-ml-nov22/view',
  },
  {
    id: 'be7-cc-nov22',
    branchName: 'Computer Engineering',
    academicYear: 'BE',
    semester: 7,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Cloud Computing',
    subjectCode: 'BE-CE-702',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_be7-cc-nov22/view',
  },
  {
    id: 'be7-dwm-nov22',
    branchName: 'Computer Engineering',
    academicYear: 'BE',
    semester: 7,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Data Warehousing & Mining',
    subjectCode: 'BE-CE-703',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_be7-dwm-nov22/view',
  },
  {
    id: 'be7-hpc-nov22',
    branchName: 'Computer Engineering',
    academicYear: 'BE',
    semester: 7,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2022,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'High Performance Computing',
    subjectCode: 'BE-CE-704',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_be7-hpc-nov22/view',
  },
  {
    id: 'be7-ml-nov23',
    branchName: 'Computer Engineering',
    academicYear: 'BE',
    semester: 7,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Machine Learning',
    subjectCode: 'BE-CE-701',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_be7-ml-nov23/view',
  },
  {
    id: 'be7-cc-nov23',
    branchName: 'Computer Engineering',
    academicYear: 'BE',
    semester: 7,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Cloud Computing',
    subjectCode: 'BE-CE-702',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_be7-cc-nov23/view',
  },
  {
    id: 'be7-dwm-nov23',
    branchName: 'Computer Engineering',
    academicYear: 'BE',
    semester: 7,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Data Warehousing & Mining',
    subjectCode: 'BE-CE-703',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_be7-dwm-nov23/view',
  },

  // ── BE Sem 8 — 2019 Pattern — May exams ──────────────────────────────────
  {
    id: 'be8-dl-may23',
    branchName: 'Computer Engineering',
    academicYear: 'BE',
    semester: 8,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Deep Learning & Applications',
    subjectCode: 'BE-CE-801',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_be8-dl-may23/view',
  },
  {
    id: 'be8-iot-may23',
    branchName: 'Computer Engineering',
    academicYear: 'BE',
    semester: 8,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Internet of Things',
    subjectCode: 'BE-CE-802',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_be8-iot-may23/view',
  },
  {
    id: 'be8-bc-may23',
    branchName: 'Computer Engineering',
    academicYear: 'BE',
    semester: 8,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Blockchain Technology',
    subjectCode: 'BE-CE-803',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_be8-bc-may23/view',
  },
  {
    id: 'be8-dip-may23',
    branchName: 'Computer Engineering',
    academicYear: 'BE',
    semester: 8,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2023,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Digital Image Processing',
    subjectCode: 'BE-CE-804',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_be8-dip-may23/view',
  },
  {
    id: 'be8-dl-may24',
    branchName: 'Computer Engineering',
    academicYear: 'BE',
    semester: 8,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2024,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Deep Learning & Applications',
    subjectCode: 'BE-CE-801',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_be8-dl-may24/view',
  },
  {
    id: 'be8-iot-may24',
    branchName: 'Computer Engineering',
    academicYear: 'BE',
    semester: 8,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2024,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Internet of Things',
    subjectCode: 'BE-CE-802',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_be8-iot-may24/view',
  },
  {
    id: 'be8-bc-may24',
    branchName: 'Computer Engineering',
    academicYear: 'BE',
    semester: 8,
    pattern: PAPER_PATTERN.P2019,
    examYear: 2024,
    examMonth: EXAM_MONTH.MAY,
    subjectName: 'Blockchain Technology',
    subjectCode: 'BE-CE-803',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_be8-bc-may24/view',
  },

  // ── SE Sem 3 — 2024 Pattern — November 2024 ──────────────────────────────
  {
    id: 'se3-dm-nov24-p24',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2024,
    examYear: 2024,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Engineering Mathematics III',
    subjectCode: 'SE-CE-301-24',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-em3-nov24-p24/view',
  },
  {
    id: 'se3-ds-nov24-p24',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2024,
    examYear: 2024,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Data Structures & Algorithms',
    subjectCode: 'SE-CE-302-24',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-dsa-nov24-p24/view',
  },
  {
    id: 'se3-de-nov24-p24',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2024,
    examYear: 2024,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Digital Circuits & Systems',
    subjectCode: 'SE-CE-303-24',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-dcs-nov24-p24/view',
  },
  {
    id: 'se3-oop-nov24-p24',
    branchName: 'Computer Engineering',
    academicYear: 'SE',
    semester: 3,
    pattern: PAPER_PATTERN.P2024,
    examYear: 2024,
    examMonth: EXAM_MONTH.NOV,
    subjectName: 'Object Oriented Programming',
    subjectCode: 'SE-CE-304-24',
    fileUrl: 'https://drive.google.com/file/d/PLACEHOLDER_se3-oop-nov24-p24/view',
  },
];

@Injectable({ providedIn: 'root' })
export class PaperService {
  getAll(): Observable<PreviousYearPaper[]> {
    return of([...MOCK_PAPERS]).pipe(delay(300));
  }
}
